  ngrinder-controller:
    image: ngrinder/controller
    container_name: ngrinder-controller
    hostname: ngrinder-controller
    ports:
      - 9080:80
      - 16001:16001
      - 12000-12009:12000-12009
    volumes:
      - /data/ngrinder/controller:/opt/ngrinder-controller
  ngrinder-agent1:
    image: ngrinder/agent
    container_name: ngrinder-agent1
    hostname: ngrinder-agent1
    volumes:
      - /data/ngrinder/agent:/opt/ngrinder-agent
    command:
      - ip:9080
  ngrinder-agent2:
    image: ngrinder/agent
    container_name: ngrinder-agent2
    hostname: ngrinder-agent2
    volumes:
      - /data/ngrinder/agent:/opt/ngrinder-agent
    command:
      - ip:9080