apiVersion: v1
kind: Service
metadata:
  name: kafka-0
  namespace: kafka
spec:
  type: NodePort
  selector:
    statefulset.kubernetes.io/pod-name: kafka-0
  ports:
    - name: inside
      protocol: TCP
      nodePort: 32010
      port: 9092
      targetPort: 9092
    - name: jmx
      protocol: TCP
      nodePort: 32016
      port: 5555
      targetPort: 5555
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-1
  namespace: kafka
spec:
  type: NodePort
  selector:
    statefulset.kubernetes.io/pod-name: kafka-1
  ports:
    - name: inside
      protocol: TCP
      nodePort: 32011
      port: 9092
      targetPort: 9092
    - name: jmx
      protocol: TCP
      nodePort: 32017
      port: 5555
      targetPort: 5555
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-2
  namespace: kafka
spec:
  type: NodePort
  selector:
    statefulset.kubernetes.io/pod-name: kafka-2
  ports:
    - name: inside
      protocol: TCP
      nodePort: 32012
      port: 9092
      targetPort: 9092
    - name: jmx
      protocol: TCP
      nodePort: 32018
      port: 5555
      targetPort: 5555
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-3
  namespace: kafka
spec:
  type: NodePort
  selector:
    statefulset.kubernetes.io/pod-name: kafka-3
  ports:
    - name: inside
      protocol: TCP
      nodePort: 32013
      port: 9092
      targetPort: 9092
    - name: jmx
      protocol: TCP
      nodePort: 32019
      port: 5555
      targetPort: 5555
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-4
  namespace: kafka
spec:
  type: NodePort
  selector:
    statefulset.kubernetes.io/pod-name: kafka-4
  ports:
    - name: inside
      protocol: TCP
      nodePort: 32014
      port: 9092
      targetPort: 9092
    - name: jmx
      protocol: TCP
      nodePort: 32020
      port: 5555
      targetPort: 5555
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-5
  namespace: kafka
spec:
  type: NodePort
  selector:
    statefulset.kubernetes.io/pod-name: kafka-5
  ports:
    - name: inside
      protocol: TCP
      nodePort: 32015
      port: 9092
      targetPort: 9092
    - name: jmx
      protocol: TCP
      nodePort: 32021
      port: 5555
      targetPort: 5555