# 每个节点均承担 Master、Data、Ingest 角色
---
apiVersion: apps/v1
kind: StatefulSet  # ES属于有状态服务
metadata:
  name: es-cluster
  namespace: default  # 数据收集都放在该命名空间下
spec:
  serviceName: elasticsearch-headless
  replicas: 3
  selector:
    matchLabels:
      app: elasticsearch  # 匹配标签
  template:
    metadata:
      labels:
        app: elasticsearch  # 给服务贴上标签
    spec:
      containers:  # 容器初始化
      - name: elasticsearch
        image: elasticsearch:7.3.3
        imagePullPolicy: IfNotPresent  # 有3种，Never,Always,IfNotPresent 分别表示只从本地拉取，直接远程拉取，先本地后远程拉取
        livenessProbe:  # 探测服务
          tcpSocket:
            port: 9200
          initialDelaySeconds: 60
          timeoutSeconds: 5
          failureThreshold: 12
        readinessProbe:
          tcpSocket:
            port: 9200
          initialDelaySeconds: 60
          timeoutSeconds: 5
          failureThreshold: 12
        resources:  # 服务分配的资源限制
            limits:
              cpu: "1000m"
              memory: "1500Mi"
            requests:
              cpu: "500m"
              memory: "512Mi"
        ports:  # 容器开放的端口
        - containerPort: 9200
          name: es-http
          protocol: TCP
        - containerPort: 9300
          name: cluster-port
          protocol: TCP
        env:  # 服务需要设置的环境变量
          - name: REQUESTS_MEMORY
            valueFrom:
              resourceFieldRef:
                resource: requests.memory
                divisor: 1Mi
          - name: node.name
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: cluster.name
            value: es-cluster
          - name: http.cors.enabled
            value: "true"
          - name: http.cors.allow-origin
            value: "*"
          - name: xpack.security.enabled
            value: "true"
          - name: xpack.security.transport.ssl.enabled
            value: "true"
          - name: xpack.security.transport.ssl.verification_mode
            value: "certificate"
          - name: xpack.security.transport.ssl.keystore.path
            value: "/usr/share/elasticsearch/config/certs/elastic-certificates.p12"
          - name: xpack.security.transport.ssl.truststore.path
            value: "/usr/share/elasticsearch/config/certs/elastic-certificates.p12"
          - name: ES_JAVA_OPTS
            value: "-Xms$(REQUESTS_MEMORY)m -Xmx$(REQUESTS_MEMORY)m"
          - name: cluster.initial_master_nodes
            value: "es-cluster-0,es-cluster-1,es-cluster-2"
          - name: discovery.seed_hosts
            value: "es-cluster-0.elasticsearch-headless,es-cluster-1.elasticsearch-headless,es-cluster-2.elasticsearch-headless"
      initContainers:  # 初始化容器一般用于开启服务之前需要先执行的某些必要步骤
      - name: vm-max-map
        image: busybox:latest  # busybox镜像，经常用于测试
        imagePullPolicy: IfNotPresent
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:  # 获取root权限，一般在容器内执行某些命令需要
          privileged: true
      - name: fd-ulimit
        image: busybox:latest
        imagePullPolicy: IfNotPresent
        command: ["sh", "-c", "ulimit -n 65535"]
        securityContext:
          privileged: true

---
kind: Service  # 提供外网访问服务方式
apiVersion: v1
metadata:
  name: elasticsearch
  namespace: default
  labels:
    app: elasticsearch
spec:
  type: NodePort
  selector:
    app: elasticsearch
  ports:
    - port: 9200
      name: es-http
      nodePort: 32111

---

apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-headless
  namespace: default
  labels:
    app: elasticsearch
spec:
  ports:
  - name: elasticsearch
    port: 9200
  selector:
    app: elasticsearch
  clusterIP: None