kind: Service
apiVersion: v1
metadata:
  name: influxdb
  namespace: kube-system
  labels:
    kubernetes.io/name: "influxdb"
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  type: NodePort
  ports:
    - name: http
      port: 8083
      protocol: TCP
      targetPort: 8083
      nodePort: 32010
    - name: api
      port: 8086
      protocol: TCP
      targetPort: 8086
      nodePort: 32011
  selector:
    k8s-app: influxdb